package nuvem_de_bolso.client;

import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author lucas
 */
public class Diretorio extends javax.swing.JFrame {

    private String selecionado = "";
    private Icon icon;
    private int action = 0;
    private String botao;
    private boolean clickou = false;
    private boolean itemCopiado = false;
    private String nomePasta = "";
    private String novoNome = "";
    private String icone = "";
    String folha = new ImageIcon("C:\\POO\\teste_POO\\folha.png").toString();
    String pasta = new ImageIcon("C:\\POO\\teste_POO\\pasta.png").toString();
    private Renderer renderer = new Renderer();
    /**
     * Creates new form Diretorio
     */
    public Diretorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        copiar = new javax.swing.JMenuItem();
        excluir = new javax.swing.JMenuItem();
        renomear = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        Cria_pasta = new javax.swing.JMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        Cria_pasta_2 = new javax.swing.JMenuItem();
        colar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaArquivos = new javax.swing.JList();
        label = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        alterna = new javax.swing.JButton();
        arquivo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        diretorio = new javax.swing.JTextField();
        voltar = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();

        copiar.setText("Copiar");
        copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(copiar);

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        jPopupMenu1.add(excluir);

        renomear.setText("Renomear");
        renomear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renomearActionPerformed(evt);
            }
        });
        jPopupMenu1.add(renomear);

        Cria_pasta.setText("Criar pasta");
        Cria_pasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cria_pastaActionPerformed(evt);
            }
        });
        jPopupMenu2.add(Cria_pasta);

        Cria_pasta_2.setText("Criar pasta");
        Cria_pasta_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cria_pasta_2ActionPerformed(evt);
            }
        });
        jPopupMenu3.add(Cria_pasta_2);

        colar.setText("Colar");
        colar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colarActionPerformed(evt);
            }
        });
        jPopupMenu3.add(colar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        listaArquivos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaArquivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaArquivosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaArquivos);

        label.setText("Nome do arquivo");

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        alterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternaActionPerformed(evt);
            }
        });

        arquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquivoActionPerformed(evt);
            }
        });

        jLabel1.setText("Diretorio");

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        atualizar.setText("Atualizar");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterna, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diretorio, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(diretorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltar)
                    .addComponent(atualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label)
                        .addComponent(cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(arquivo))
                    .addComponent(alterna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(421, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void arquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arquivoActionPerformed

    private void alternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternaActionPerformed
        // TODO add your handling code here:
        action = 3;
    }//GEN-LAST:event_alternaActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        action = -1;
    }//GEN-LAST:event_cancelarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        action = 2;
    }//GEN-LAST:event_voltarActionPerformed

    private void listaArquivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaArquivosMouseClicked
        // TODO add your handling code here:
        try{
            if(SwingUtilities.isLeftMouseButton(evt)){
                selecionado = ((ImgsNText)(listaArquivos.getSelectedValue())).getName();
                icone = ((ImgsNText)(listaArquivos.getSelectedValue())).getImg().toString();
                setClickou(true);

                if (evt.getClickCount() == 2){

                    if (botao.equals("salvar")){
                        if (icone.equals(folha)){action = -10;}
                        else{action  = 1;}  
                    }
                    if (botao.equals("abrir")){
                        if (icone.equals(pasta)){action = 1;}
                        else{action  = 3;}  
                    }
                    setClickou(false);
                }

            }
            
            if(SwingUtilities.isRightMouseButton(evt) && clickou == true){
                jPopupMenu1.show(this,evt.getX(),evt.getY());
            }
            if(SwingUtilities.isRightMouseButton(evt) && clickou == false && itemCopiado == false){
                jPopupMenu2.show(this,evt.getX(),evt.getY());
            }
            if(SwingUtilities.isRightMouseButton(evt) && clickou == false && itemCopiado == true){
                jPopupMenu3.show(this,evt.getX(),evt.getY());
            }
            
            
        }catch(Exception e){}     
    }//GEN-LAST:event_listaArquivosMouseClicked

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        action = 5;
    }//GEN-LAST:event_excluirActionPerformed

    private void copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarActionPerformed
        // TODO add your handling code here:
        action = 6;
        itemCopiado = true;
    }//GEN-LAST:event_copiarActionPerformed

    private void Cria_pastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cria_pastaActionPerformed
        // TODO add your handling code here:
        setNomePasta(JOptionPane.showInputDialog("Digite o nome da pasta a ser criada"));
        if (getNomePasta() != null && getNomePasta().length() > 1){
            action = 4;
        }
        else{
            action = -10;
        }
    }//GEN-LAST:event_Cria_pastaActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
        action = 0;
    }//GEN-LAST:event_atualizarActionPerformed

    private void colarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colarActionPerformed
        // TODO add your handling code here:
        action = 7;
    }//GEN-LAST:event_colarActionPerformed

    private void Cria_pasta_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cria_pasta_2ActionPerformed
        // TODO add your handling code here:
        setNomePasta(JOptionPane.showInputDialog("Digite o nome da pasta a ser criada"));
        if (getNomePasta() != null && getNomePasta().length() > 1){
            action = 4;
        }
        else{
            action = -10;
        }
    }//GEN-LAST:event_Cria_pasta_2ActionPerformed

    private void renomearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renomearActionPerformed
        // TODO add your handling code here:
        this.novoNome = JOptionPane.showInputDialog("Digite o novo nome:");
        if (novoNome != null && novoNome.length() > 1){
            action = 8;
        }
        else{
            action = -10;
        }
    }//GEN-LAST:event_renomearActionPerformed

    /**
     * @param args
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diretorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diretorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diretorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diretorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diretorio().setVisible(true);
            }
        });
    }
    public void setArquivo(String nome){
        arquivo.setText(nome);
    }
    public void setList(DefaultListModel list){
        listaArquivos.clearSelection();
        listaArquivos.setCellRenderer(renderer);
        for(int i = 0; i < list.getSize(); i++){}
        listaArquivos.setModel(list);
    }
    public int getAction(){
        return action;
    }
    public String getSelecionado(){
        return selecionado;
    }
    
    public void setAction(int n){
        action = n;
    }
    
    public void setDiretorio(String dir){
        diretorio.setText(dir);
    }
    
    public String getPasta(){
        return diretorio.getText();
    }
    
    public String getDiretorio(){
        if (botao.equals("salvar")){ 
            String dir = diretorio.getText() + File.separator +arquivo.getText();
            return dir;
        }
        if (botao.equals("abrir")){
            String dir = diretorio.getText() + File.separator + selecionado;
            return dir;
        }
        return null;
    }
    
    public void setBotaoSalvar(){
        alterna.setText("Salvar");
        botao = "salvar";
    }
    
    public void setBotaoAbrir(){
        alterna.setText("Abrir");
        botao = "abrir";
    }
    
    public String getNomePasta() {
        return nomePasta;
    }

    public void setNomePasta(String nomePasta) {
        this.nomePasta = nomePasta;
    } 
    
    public void setClickou(boolean clickou) {
        this.clickou = clickou;
    }
    
    public String getNovoNome(){
        return this.novoNome;
    }
    
    public void SetNovoNome(String nome){
        this.novoNome = nome;
    }

    public String getIcone(){
        return this.icone;
    }
    
    public String getIconeFolha(){
        return this.folha;
    }
    
    public String getIconePasta(){
        return this.pasta;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cria_pasta;
    private javax.swing.JMenuItem Cria_pasta_2;
    private javax.swing.JButton alterna;
    private javax.swing.JTextField arquivo;
    private javax.swing.JButton atualizar;
    private javax.swing.JButton cancelar;
    private javax.swing.JMenuItem colar;
    private javax.swing.JMenuItem copiar;
    private javax.swing.JTextField diretorio;
    private javax.swing.JMenuItem excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JList listaArquivos;
    private javax.swing.JMenuItem renomear;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
